name: protonvpn
adopt-info: protonvpn
summary: A Linux CLI for ProtonVPN. Written in Python.
description: |
  ProtonVPN-CLI is a full rewrite of the bash protonvpn-cli in Python, 
  which adds more features and functionality with the purpose of 
  improving readability, speed and reliability.
  
license: GPL-3.0

base: core20
grade: stable 
confinement: strict

apps:
  protonvpn:
    command: bin/protonvpn
    extensions:
      - gnome-3-38    
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3.8/dist-packages
    plugs:  
      - network
      - network-bind
      - network-control
      - home   
         
parts: 
  protonvpn:
    source: https://github.com/ProtonVPN/linux-app
    source-type: git
    plugin: python
    build-environment:
      - SNAPCRAFT_PYTHON_INTERPRETER: python3.8
      - PATH: $SNAPCRAFT_PART_INSTALL/bin:$PATH
      - PYTHONPATH: ''
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
      
    build-packages:
      - python3-gi
      - python3-psutil
      - python3-pip
      - python3-testresources
    after: 
      - protonvpn-nm-lib
      
    stage-packages:
      - python3-gi
      - python3-psutil
      - gir1.2-appindicator3-0.1
    after: 
      - protonvpn-nm-lib
      
  protonvpn-nm-lib:
    source: https://github.com/ProtonVPN/protonvpn-nm-lib
    source-type: git
    plugin: python
    build-environment:
      - SNAPCRAFT_PYTHON_INTERPRETER: python3.8
      - PATH: $SNAPCRAFT_PART_INSTALL/bin:$PATH
      - PYTHONPATH: ''
  
    build-packages:
      - pkg-config 
      - network-manager 
      - network-manager-openvpn 
      - openvpn 
      - libcairo2-dev 
      - libgirepository1.0-dev 
      - gir1.2-nm-1.0 
      - dbus-x11 
      - libsecret-tools 
      - gnome-keyring
      - python3-xdg
      
    stage-packages:
      - pkg-config 
      - network-manager 
      - network-manager-openvpn 
      - openvpn 
      - libcairo2-dev 
      - libgirepository1.0-dev 
      - gir1.2-nm-1.0 
      - dbus-x11 
      - libsecret-tools 
      - gnome-keyring   
      - python3-xdg
