name: protonvpn
adopt-info: protonvpn
summary: A Linux CLI for ProtonVPN. Written in Python.
description: |
  ProtonVPN-CLI is a full rewrite of the bash protonvpn-cli in Python, 
  which adds more features and functionality with the purpose of 
  improving readability, speed and reliability.
  
license: GPL-3.0

base: core18
grade: stable 
confinement: strict

apps:
  protonvpn:
    command: python3 $SNAP/usr/local/bin/protonvpn
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:  
      - network
      - network-bind
      - network-control
      - home   
         
parts: 
  protonvpn:
    source: https://github.com/ProtonVPN/linux-cli
    source-type: git
    plugin: nil
    
    override-build: |
      pip3 install protonvpn-cli
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
      
    build-packages:
      - python3-all-dev
      - python3-setuptools
      - python3-pip
      
    stage-packages:
      - python3
